### ISSUE TITLE
Could not complete Mojo execution...

### ISSUE THREAD

**Issue by sigterm9kill** [cmu-db/benchbase#100]
after: 
git clone --depth 1 https://github.com/cmu-db/benchbase.git
cd benchbase
./mvnw clean package

Returns: 
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< com.oltpbenchmark:benchbase >---------------------
[INFO] Building BenchBase 2021-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ benchbase ---
[INFO] 
[INFO] --- git-commit-id-plugin:4.9.10:revision (get-the-git-infos) @ benchbase ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.059 s
[INFO] Finished at: 2021-12-29T11:10:32-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.9.10:revision (get-the-git-infos) on project benchbase: Could not complete Mojo execution...: pl.project13.core.NativeGitProvider$NativeCommandException: Git command exited with invalid status [128]: directory: `/root/benchbase`, command: `git log -1 --pretty=format:%an --no-show-signature HEAD`, stdout: ``, stderr: `fatal: unrecognized argument: --no-show-signature` -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by apavlo** [comment]
I think something is wrong with your environment. Can you provide more info (distro, jdk/maven version)?

**Comment by sigterm9kill** [comment]
I went to archived oltp and simply installed with docker.  Thanks anyway.  

Respectfully,

Sean O’Brien

**Comment by apavlo** [comment]
It would still be helpful to know what went wrong so that we can fix it for future people.

**Comment by sigterm9kill** [comment]
I was able to correct MY error, please forgive.  This works very nicely.    

Respectfully,

Sean O’Brien
