### ISSUE TITLE
The project is not going under java 11.

### ISSUE THREAD

**Issue by prom1se** [cmu-db/benchbase#109]
If you try to build a project, we get an error:
```
java: error: release version 17 not supported
Module benchbase SDK 11 is not compatible with the source version 17.
Upgrade Module SDK in project settings to 17 or higher. Open project settings.
```
Plus, there are several places in the codebase (mostly switches) that are only available from older versions.

We need to either change the Readme:
https://github.com/cmu-db/benchbase/blob/fd4a69c40b969b00b8abbb3d465a360b866988c8/README.md?plain=1#L181

or make edits to the code.

**Comment by lmwnshn** [comment]
We decided to move to 17 in #72, we do need to update the docs. Thanks for the issue.

**Comment by timveil** [comment]
doc was updated as part of issue #97 and PR #121.  As @lmwnshn we have moved to JDK 17
