### ISSUE TITLE
Add configurable remote warehouse ratio for New Order transactions of TPC-C

### ISSUE THREAD

**Issue by sirafantas** [cmu-db/benchbase#112]
I would like to support configurable remote warehouse ratios to evaluate distributed transaction processing performance and am considering how this could be implemented in BenchBase.

I was able to find the part that gets the configuration values from the XML, but my concern is that implementing a configurable remote warehouse ratio here would affect all other workloads.

Do you have any ideas for implementing such a feature?

```diff
diff --git a/src/main/java/com/oltpbenchmark/DBWorkload.java b/src/main/java/com/oltpbenchmark/DBWorkload.java
index df41b301..7d560e84 100644
--- a/src/main/java/com/oltpbenchmark/DBWorkload.java
+++ b/src/main/java/com/oltpbenchmark/DBWorkload.java
@@ -210,6 +210,11 @@ public class DBWorkload {
                     postExecutionWait = xmlConfig.getLong(key + "/postExecutionWait");
                 }
 
+                double remoteWarehouseRatio = 1.0;
+                if (xmlConfig.containsKey(key + "/remoteWarehouseRatio")) {
+                    remoteWarehouseRatio = xmlConfig.getDouble(key + "/premoteWarehouseRatio");
+                }
+
                 TransactionType tmpType = bench.initTransactionType(txnName, txnId + txnIdOffset, preExecutionWait, postExecutionWait);
 
                 // Keep a reference for filtering
```

**Comment by apavlo** [comment]
You can stick anything in the XML configuration file and pull it out in the benchmark specific code. See this example from `TPCHLoader`:

https://github.com/cmu-db/benchbase/blob/main/src/main/java/com/oltpbenchmark/benchmarks/tpch/TPCHLoader.java#L410
