### ISSUE TITLE
Glitch phenomenon during testing

### ISSUE THREAD

**Issue by CES-dengzeyuan** [cmu-db/benchbase#148]
Hi Guys, excellent tool. Could you tell me how the glitch phenomenon appears during testing? I want to execute the TPC-C benchmark by PostgreSQL. 

I generate the database data in advance and loop the following command to run a quick start. I run it on a single computer and use the default config.xml.

java -jar benchbase.jar -b tpcc -c config/postgres/sample_tpcc_config.xml --execute=true

    
    <terminals>1</terminals>
    <works>
        <work>
            <time>60</time>
            <rate>10000</rate>
            <weights>45,43,4,4,4</weights>
        </work>
    </works>

![4-9-result-1](https://user-images.githubusercontent.com/46039524/162695536-ea96f481-d0e3-4b82-9a6b-6e08768a9ee7.png)

The red line in Fig1 is the throughput, while the blue line is the system's latency. I ran the TPC-C benchmark without modifying any parameters 60 times. Experimental results show large fluctuations in throughput and latency. I wonder why they happen.

Thanks for help.

**Comment by apavlo** [comment]
This oscillation is due to Postgres. We've seen it in our own experiments. It is likely the background writer / autovacuum. Try running it on MySQL and see whether you see the same thing.

Also, TPC-C is an INSERT heavy workload. So at 20k txn/sec, you are creating a lot of new tuples.

**Comment by apavlo** [comment]
What is the unit of measurement in your graph? Milliseconds? Seconds?

**Comment by CES-dengzeyuan** [comment]
I used python to write a script that loops through the Quick-start command for several times. I just test the QuickStart without changing any configuration on benchbase and MySQL.

My code just like below:
for i in range(100):
    os.system(“ java -jar benchbase.jar -b tpcc -c config/mysql/sample_tpcc_config.xml --execute=true”)

**Comment by apavlo** [comment]
I think you're graphing milliseconds. So your oscillation in performance is on the order of 800 microseconds. That's noise and there is not way to get more stable numbers.
