### ISSUE TITLE
Dynamically import benchmark as opposed to having to statically compile it in

### ISSUE THREAD

**Issue by shuhaowu** [cmu-db/benchbase#149]
If I want to create a private benchmark, right now it seems like the only way is to fork benchbase and add the custom benchmark. It would be nice if that code can be maintained separately, and upstream-benchbase can be used directly.

A low priority feature request, but may help the adoption of benchbase a bit more.

**Comment by bpkroth** [comment]
@jcamachor

**Comment by bpkroth** [comment]
Hi, I think support for this has been added via the `templated` benchmarks introduced in #301.

Please let us know if there's additional features you think are still missing.  Cheers!
