### ISSUE TITLE
The isolation level and general query log

### ISSUE THREAD

**Issue by gogo9th** [cmu-db/benchbase#189]
Hi,

In the XML configuration file, if we have the following isolation level for TPCC:

`<isolation>TRANSACTION_SERIALIZABLE</isolation>`

And if we have two transactions issued as follows:

t=1: Payment
t=2: Delivery

Then, in the MySQL database system's general query log, all sub-queries of the Payment transaction (t=1) will appear before all sub-queries of the Delivery transaction (t=2). Is this correct? (In other words, the order of the sub-queries of any two transactions cannot be mixed in case of TRANSACTION_SERIALIZABLE, right?)

**Comment by gogo9th** [comment]
Another question is, 

TPC-C's NewOrder transaction's Java source code is as follows:

```
benchbase/src/main/java/com/oltpbenchmark/benchmarks/tpcc/procedures/NewOrder.java:
...
        getCustomer(conn, w_id, d_id, c_id);
        getWarehouse(conn, w_id);
        int d_next_o_id = getDistrict(conn, w_id, d_id);
        updateDistrict(conn, w_id, d_id);
        insertOpenOrder(conn, w_id, d_id, c_id, o_ol_cnt, o_all_local, d_next_o_id);
        insertNewOrder(conn, w_id, d_id, d_next_o_id);
...
```
However, since NewOrder is a transaction, if `insertOpenOrder` or `insertNewOrder` fails, then `updateDistrict` should be aborted (i.e., rolled back), isn't it? Because I do not see any rollback logic in the source code...

**Comment by gogo9th** [comment]
Thanks for the URL. 

Q1. So you enforce that if a transaction fails in the middle of running its queries, then it does not roll back the already executed queries, right? I was assuming that we should roll back the executed queries in such a case, because in reality, if the `insertNewOrder` query fails while running the `NewOrder` transaction, then the effect of the previously executed `updateDistrict` and `insertOpenOrder` queries should be rolled back, otherwise the `OpenOrder` table would end up with a dangling inconsistent state (because there is actually no new order). But you don't enforce rolling back in such cases, correct?

Q2. In your `TRANSACTION_SERIALIZABLE` mode, there is no interleaving transactions during the benchmark execution, correct?

**Comment by gogo9th** [comment]
Regarding Q1, I think you actually roll back upon query execution failure:

[https://github.com/cmu-db/benchbase/blob/d9a6a7b7d0b9c315a4222f02fcff75909be460cb/src/main/java/com/oltpbenchmark/api/Worker.java#L416](https://github.com/cmu-db/benchbase/blob/d9a6a7b7d0b9c315a4222f02fcff75909be460cb/src/main/java/com/oltpbenchmark/api/Worker.java#L416)

**Comment by apavlo** [comment]
You are misunderstanding who is doing what. The DBMS handles the isolation levels, interleaving, and rollbacks. The application code (i.e., BenchBase) does not do partial rollback.s

**Comment by gogo9th** [comment]
> The application code (i.e., BenchBase) does not do partial rollback
I think I didn't misunderstand, but I think we misunderstood what each other was trying to say. I do get what you're saying and what you are saying is what I assumed. But maybe my wording was poor. Yes, eventually it is the DBMS who does the rollback, but what I meant was that it is your BenchBase application code who detects the case for rollbacks and issues the rollback command to the DBMS. In line 416 of Worker.java, the Java application code executes this:

```
                } catch (SQLException ex) {
                    conn.rollback();
```
It is your application code who detects this exception and commands the DBMS to rollback, not the DBMS. If we want the DBMS to handle rollback upon exception, we need to do something like this:
`https://sql-bits.com/mariadb-rollback-the-transaction-if-a-warning-occurs/`
... which is a very tedious way. I don't understand why MySQL or MariaDB implements the functionality such that we can handle exceptions within a transaction (not just within a procedure).
