### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by gogo9th** [cmu-db/benchbase#190]
If I set the `config/*/*.xml` configuration file's `<rate>` to a high value like 100000, I get **java.lang.OutOfMemoryError**. I could remove this error by changing the following code lines:

https://github.com/cmu-db/benchbase/blob/d9a6a7b7d0b9c315a4222f02fcff75909be460cb/src/main/java/com/oltpbenchmark/WorkloadState.java#L74-L83

```
                for (int i = 0; i < amount; ++i) {
                    workQueue.add(new SubmittedProcedure(currentPhase.chooseTransaction()));
                }
            }

            // Can't keep up with current rate? Remove the oldest transactions
            // (from the front of the queue).
            while (workQueue.size() > RATE_QUEUE_LIMIT) {
                workQueue.remove();
            }
```

as follows:

```
                for (int i = 0; i < amount && workQueueSize() <= RATE_QUEUE_LIMIT; ++i) {
                    workQueue.add(new SubmittedProcedure(currentPhase.chooseTransaction()));
                }
            }
```

(i.e., skipping to enqueue overflowing transactions in the first place instead of enqueuing→dequeuing them.)

**Comment by apavlo** [comment]
Can you submit a PR so that I can examine it with context?

Why not just increase the JVM heap size?
