### ISSUE TITLE
Incorrect SQLState value in Worker.java

### ISSUE THREAD

**Issue by AroraAsh** [cmu-db/benchbase#220]
In Worker when a retryable exception occurs the sqlstate and the error code are checked to see if the transaction is retryable or not. 
The sql state and error code for the lock wait timeout exception are written as 41000 and 1205 respectively.
According to the mysql link https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-error-sqlstates.html, the correct sqlstate is 40001.

**Comment by apavlo** [comment]
@AroraAsh Thanks for reaching out. Can you send a PR?

**Comment by AroraAsh** [comment]
Done, I also wanted to ask something else, The paper for oltpbench mentions the use of ditributed clients but i dont see anything in the code for that, is that something not included in the features now ?
