### ISSUE TITLE
Add SQL Server to CI.

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/benchbase#23]
SQL Server has a Docker image: https://hub.docker.com/_/microsoft-mssql-server

We may be able to integrate this into our GitHub Actions workflow: https://github.com/cmu-db/benchbase/blob/main/.github/workflows/maven.yml

**Comment by apavlo** [comment]
Merged in #147 but only for TPC-C and TPC-H. Still need to support other benchmarks.

**Comment by bpkroth** [comment]
Adding most other benchmarks in #264.
There are two that are currently failing due to bigint overflow exceptions (auctionmark and seats).
Going to make a separate issue for those though.
