### ISSUE TITLE
Extend Database

### ISSUE THREAD

**Issue by Yummy813** [cmu-db/benchbase#236]
How do I configure dialect packs？
< dialect>config/dialects/tpcc_ dialects.xml</dialect>
What should be written in this xml file?

**Comment by bpkroth** [comment]
Easiest thing is probably to look at the code for examples:
https://github.com/cmu-db/benchbase/tree/main/src/main/resources/benchmarks/tpcc
In that directory there is a `dialect-{db_type}.xml` file that helps override the SQL to use for that `{db_type}`.
