### ISSUE TITLE
Which benchmarks are OLAP benchmarks?

### ISSUE THREAD

**Issue by minseok1335** [cmu-db/benchbase#303]
I want to profile the OLAP benchmarks, but for any benchmarks included in your project, I can't distinguish which benchmarks are whether they are OLTP or OLAP because there are no comments. 

Which of the benchmarks included in the project is the OLAP benchmark?

Thank you for your time.

**Comment by bpkroth** [comment]
TPC-H and CH-benCHmark are the main ones to look at:
https://github.com/cmu-db/benchbase/wiki
