### ISSUE TITLE
Detect closed connections and automatically attempt to reconnect them.

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/benchbase#32]
The Worker creates a connection [here](https://github.com/cmu-db/benchbase/blob/main/src/main/java/com/oltpbenchmark/api/Worker.java#L75) in its constructor.

However, if the connection is closed by the DBMS (e.g., hammer a CPU-limited PostgreSQL read replica with reads to the point of replication replay being blocked), the Worker does not recover and tries to execute on the closed connection.

We would like the closed connection to be reopened. Maybe add a setting for whether this behavior should happen.

**Comment by bpkroth** [comment]
FYI, this got merged finally.  Let us know if it addresses your concerns.  Thanks!
