### ISSUE TITLE
A minor inefficiency in the TPCC benchmark's Payment transaction

### ISSUE THREAD

**Issue by gogo9th** [cmu-db/benchbase#324]
I think the [getCData() function](https://github.com/cmu-db/benchbase/blob/12e3acc56dac5b15887933a8a831b18de5a688ee/src/main/java/com/oltpbenchmark/benchmarks/tpcc/procedures/Payment.java#L366) is unnecessary,because the prior [getCustomer() function](https://github.com/cmu-db/benchbase/blob/12e3acc56dac5b15887933a8a831b18de5a688ee/src/main/java/com/oltpbenchmark/benchmarks/tpcc/procedures/Payment.java#L309) can get this same customer's C_DATA. If we incorporate getCData() into getCustomer(), then we can save 1 SELECT query.

**Comment by apavlo** [comment]
@gogo9th You are correct except that the extra query is in the TPC-C spec (see page 110):

https://hstore.cs.brown.edu/wordpress/wp-content/uploads/2011/07/tpcc_current.pdf

So we need to keep it.
