### ISSUE TITLE
Postgres TPC-C Output Explanation

### ISSUE THREAD

**Issue by superctj** [cmu-db/benchbase#388]
Hi, thank you for open-sourcing this great workload generation framework, which is super helpful! I am new in this space and it is not straightforward for me to understand the execution outputs. Particularly, I was executing the TPC-C benchmark over Postgres. A screenshot of the outputs is shown below. I was wondering what the line of Aborted Transactions implies in this case.
<img width="782" alt="Screen Shot 2023-11-07 at 5 51 14 PM" src="https://github.com/cmu-db/benchbase/assets/33765174/e35fd4bf-0be5-4c2b-ade6-ee6ca4ab0d64">

**Comment by apavlo** [comment]
The TPC-C spec specifies that some percentage of `NewOrder` transactions are supposed to abort. The line of code is here:

https://github.com/cmu-db/benchbase/blob/main/src/main/java/com/oltpbenchmark/benchmarks/tpcc/procedures/NewOrder.java#L278

This is not an error. These are expected.

**Comment by superctj** [comment]
Thank you Andy for the quick response! I totally agree this is not an error but a question. I personally feel it is better to label this issue as question rather than invalid.
