### ISSUE TITLE
Question: How to send a query to multiple nodes

### ISSUE THREAD

**Issue by sirafantas** [cmu-db/benchbase#96]
When benchmarking a database that has multiple nodes accepting queries, such as CockroachDB, how do you expect queries to be distributed to those nodes? I think the simplest solution is to run HAProxy on a machine running BenchBase.

**Comment by timveil** [comment]
@y-sira I can't speak for other distributed databases but that is exactly what you would do for CockroachDB.  Have a look at the docker example here... https://github.com/cmu-db/benchbase/tree/main/docker/cockroach-latest.  It is definitely a best practice with CockroachDB to front your cluster with some sort of load balancer and then point Benchbase (or other application) to the url of the load balancer instead of individual nodes.  This is what the above Docker example does.

**Comment by timveil** [comment]
> I think the simplest solution is to run HAProxy on a machine running BenchBase.

once small caveat... I would recommend running your load balancer and Benchbase client on different machines.

**Comment by sirafantas** [comment]
Thank you for answering. I asked this because the TPC-C implementation of YugabyteDB (a fork of OLTPBenchmark) supports queries on multiple nodes. You also claim that BenchBase is battery included. I wonder why you decided not to implement the load balancer feature in BenchBase.

> I would recommend running your load balancer and Benchbase client on different machines.

Yes, it's better. 

One of my concerns when running load balancers on different machines is the messaging cost. Putting the load balancer between the client and database nodes complicates the analysis of performance, especially latency. IMO, it is preferable to support load balancers on the benchmark program side, as long as the load balancer does not become a bottleneck.

**Comment by timveil** [comment]
I can't speak for yugabyte best practices or their fork but Cockroach considers a load balancer in front of the nodes to be a best practice and the recommended configuration for production workloads.  However, If you prefer not to use a load balancer then you can specify multiple hosts in the jdbc url and allow the postgres jdbc driver to randomly select a node.  Given that CockroachDB is postgres wire compatible, this approach works if you want to eliminate the LB.  For example, this is a valid postgres url... `jdbc:postgresql://node1,node2,node3/accounting?loadBalanceHosts=true`.  See https://jdbc.postgresql.org/documentation/head/connect.html
